Make most constants private
rubocop-hq/rubocop-ast pull request #114
Opened 2020-09-15 21:26 UTC by marcandre

Constants for node.rb are left as is (other cops depend on them)
Constants for node_pattern.rb are left as is (whole class is @api private)

2020-09-18 05:35 UTC, bbatsov approved these changes

2020-09-25 21:11 UTC, sergeev17 requested changes

2020-09-25 21:11 UTC, sergeev17 commented on lib/rubocop/ast/node.rb
>        ASSIGNMENTS = (EQUALS_ASSIGNMENTS + SHORTHAND_ASSIGNMENTS).freeze
-1
```suggestion
       ASSIGNMENTS = 8```suggestion
       ASSIGNMENTS = (EQUALS_ASSIGNMENTS + SHORTHAND_ASSIGNMENTS).freeze
```
(EQUALS_ASSIGNMENTS + SHORTHAND_ASSIGNMENTS).freeze
```

2020-09-25 21:14 UTC, sergeev17 commented
```suggestion

```

2020-09-25 21:15 UTC, sergeev17 commented on lib/rubocop/ast/node.rb
>        ASSIGNMENTS = (EQUALS_ASSIGNMENTS + SHORTHAND_ASSIGNMENTS).freeze
```suggestion
2**@_[]()_**

2020-09-27 04:35 UTC, merged